/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4509156956024080462L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.example.kafka\",\"fields\":[{\"name\":\"orderId\",\"type\":\"int\"},{\"name\":\"user\",\"type\":{\"type\":\"record\",\"name\":\"UserInfo\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"phone\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"email\",\"type\":\"string\"}]}},{\"name\":\"shippingAddress\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"zipCode\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\",\"default\":\"España\"}]}},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Item\",\"fields\":[{\"name\":\"productId\",\"type\":\"int\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"price\",\"type\":\"float\"}]}}},{\"name\":\"totalPrice\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Order> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Order to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Order from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Order instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int orderId;
  private com.example.kafka.UserInfo user;
  private com.example.kafka.Address shippingAddress;
  private java.util.List<com.example.kafka.Item> items;
  private float totalPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param user The new value for user
   * @param shippingAddress The new value for shippingAddress
   * @param items The new value for items
   * @param totalPrice The new value for totalPrice
   */
  public Order(java.lang.Integer orderId, com.example.kafka.UserInfo user, com.example.kafka.Address shippingAddress, java.util.List<com.example.kafka.Item> items, java.lang.Float totalPrice) {
    this.orderId = orderId;
    this.user = user;
    this.shippingAddress = shippingAddress;
    this.items = items;
    this.totalPrice = totalPrice;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return user;
    case 2: return shippingAddress;
    case 3: return items;
    case 4: return totalPrice;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.Integer)value$; break;
    case 1: user = (com.example.kafka.UserInfo)value$; break;
    case 2: shippingAddress = (com.example.kafka.Address)value$; break;
    case 3: items = (java.util.List<com.example.kafka.Item>)value$; break;
    case 4: totalPrice = (java.lang.Float)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public int getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(int value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'user' field.
   * @return The value of the 'user' field.
   */
  public com.example.kafka.UserInfo getUser() {
    return user;
  }


  /**
   * Sets the value of the 'user' field.
   * @param value the value to set.
   */
  public void setUser(com.example.kafka.UserInfo value) {
    this.user = value;
  }

  /**
   * Gets the value of the 'shippingAddress' field.
   * @return The value of the 'shippingAddress' field.
   */
  public com.example.kafka.Address getShippingAddress() {
    return shippingAddress;
  }


  /**
   * Sets the value of the 'shippingAddress' field.
   * @param value the value to set.
   */
  public void setShippingAddress(com.example.kafka.Address value) {
    this.shippingAddress = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<com.example.kafka.Item> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.example.kafka.Item> value) {
    this.items = value;
  }

  /**
   * Gets the value of the 'totalPrice' field.
   * @return The value of the 'totalPrice' field.
   */
  public float getTotalPrice() {
    return totalPrice;
  }


  /**
   * Sets the value of the 'totalPrice' field.
   * @param value the value to set.
   */
  public void setTotalPrice(float value) {
    this.totalPrice = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.example.kafka.Order.Builder newBuilder() {
    return new com.example.kafka.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.example.kafka.Order.Builder newBuilder(com.example.kafka.Order.Builder other) {
    if (other == null) {
      return new com.example.kafka.Order.Builder();
    } else {
      return new com.example.kafka.Order.Builder(other);
    }
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.example.kafka.Order.Builder newBuilder(com.example.kafka.Order other) {
    if (other == null) {
      return new com.example.kafka.Order.Builder();
    } else {
      return new com.example.kafka.Order.Builder(other);
    }
  }

  /**
   * RecordBuilder for Order instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private int orderId;
    private com.example.kafka.UserInfo user;
    private com.example.kafka.UserInfo.Builder userBuilder;
    private com.example.kafka.Address shippingAddress;
    private com.example.kafka.Address.Builder shippingAddressBuilder;
    private java.util.List<com.example.kafka.Item> items;
    private float totalPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafka.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.user)) {
        this.user = data().deepCopy(fields()[1].schema(), other.user);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasUserBuilder()) {
        this.userBuilder = com.example.kafka.UserInfo.newBuilder(other.getUserBuilder());
      }
      if (isValidValue(fields()[2], other.shippingAddress)) {
        this.shippingAddress = data().deepCopy(fields()[2].schema(), other.shippingAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasShippingAddressBuilder()) {
        this.shippingAddressBuilder = com.example.kafka.Address.newBuilder(other.getShippingAddressBuilder());
      }
      if (isValidValue(fields()[3], other.items)) {
        this.items = data().deepCopy(fields()[3].schema(), other.items);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[4].schema(), other.totalPrice);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafka.Order other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.user)) {
        this.user = data().deepCopy(fields()[1].schema(), other.user);
        fieldSetFlags()[1] = true;
      }
      this.userBuilder = null;
      if (isValidValue(fields()[2], other.shippingAddress)) {
        this.shippingAddress = data().deepCopy(fields()[2].schema(), other.shippingAddress);
        fieldSetFlags()[2] = true;
      }
      this.shippingAddressBuilder = null;
      if (isValidValue(fields()[3], other.items)) {
        this.items = data().deepCopy(fields()[3].schema(), other.items);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[4].schema(), other.totalPrice);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public int getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder setOrderId(int value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'user' field.
      * @return The value.
      */
    public com.example.kafka.UserInfo getUser() {
      return user;
    }


    /**
      * Sets the value of the 'user' field.
      * @param value The value of 'user'.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder setUser(com.example.kafka.UserInfo value) {
      validate(fields()[1], value);
      this.userBuilder = null;
      this.user = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'user' field has been set.
      * @return True if the 'user' field has been set, false otherwise.
      */
    public boolean hasUser() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'user' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.kafka.UserInfo.Builder getUserBuilder() {
      if (userBuilder == null) {
        if (hasUser()) {
          setUserBuilder(com.example.kafka.UserInfo.newBuilder(user));
        } else {
          setUserBuilder(com.example.kafka.UserInfo.newBuilder());
        }
      }
      return userBuilder;
    }

    /**
     * Sets the Builder instance for the 'user' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.kafka.Order.Builder setUserBuilder(com.example.kafka.UserInfo.Builder value) {
      clearUser();
      userBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'user' field has an active Builder instance
     * @return True if the 'user' field has an active Builder instance
     */
    public boolean hasUserBuilder() {
      return userBuilder != null;
    }

    /**
      * Clears the value of the 'user' field.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder clearUser() {
      user = null;
      userBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'shippingAddress' field.
      * @return The value.
      */
    public com.example.kafka.Address getShippingAddress() {
      return shippingAddress;
    }


    /**
      * Sets the value of the 'shippingAddress' field.
      * @param value The value of 'shippingAddress'.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder setShippingAddress(com.example.kafka.Address value) {
      validate(fields()[2], value);
      this.shippingAddressBuilder = null;
      this.shippingAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'shippingAddress' field has been set.
      * @return True if the 'shippingAddress' field has been set, false otherwise.
      */
    public boolean hasShippingAddress() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'shippingAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.kafka.Address.Builder getShippingAddressBuilder() {
      if (shippingAddressBuilder == null) {
        if (hasShippingAddress()) {
          setShippingAddressBuilder(com.example.kafka.Address.newBuilder(shippingAddress));
        } else {
          setShippingAddressBuilder(com.example.kafka.Address.newBuilder());
        }
      }
      return shippingAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'shippingAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.kafka.Order.Builder setShippingAddressBuilder(com.example.kafka.Address.Builder value) {
      clearShippingAddress();
      shippingAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'shippingAddress' field has an active Builder instance
     * @return True if the 'shippingAddress' field has an active Builder instance
     */
    public boolean hasShippingAddressBuilder() {
      return shippingAddressBuilder != null;
    }

    /**
      * Clears the value of the 'shippingAddress' field.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder clearShippingAddress() {
      shippingAddress = null;
      shippingAddressBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<com.example.kafka.Item> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder setItems(java.util.List<com.example.kafka.Item> value) {
      validate(fields()[3], value);
      this.items = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder clearItems() {
      items = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalPrice' field.
      * @return The value.
      */
    public float getTotalPrice() {
      return totalPrice;
    }


    /**
      * Sets the value of the 'totalPrice' field.
      * @param value The value of 'totalPrice'.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder setTotalPrice(float value) {
      validate(fields()[4], value);
      this.totalPrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalPrice' field has been set.
      * @return True if the 'totalPrice' field has been set, false otherwise.
      */
    public boolean hasTotalPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalPrice' field.
      * @return This builder.
      */
    public com.example.kafka.Order.Builder clearTotalPrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.Integer) defaultValue(fields()[0]);
        if (userBuilder != null) {
          try {
            record.user = this.userBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("user"));
            throw e;
          }
        } else {
          record.user = fieldSetFlags()[1] ? this.user : (com.example.kafka.UserInfo) defaultValue(fields()[1]);
        }
        if (shippingAddressBuilder != null) {
          try {
            record.shippingAddress = this.shippingAddressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("shippingAddress"));
            throw e;
          }
        } else {
          record.shippingAddress = fieldSetFlags()[2] ? this.shippingAddress : (com.example.kafka.Address) defaultValue(fields()[2]);
        }
        record.items = fieldSetFlags()[3] ? this.items : (java.util.List<com.example.kafka.Item>) defaultValue(fields()[3]);
        record.totalPrice = fieldSetFlags()[4] ? this.totalPrice : (java.lang.Float) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.orderId);

    this.user.customEncode(out);

    this.shippingAddress.customEncode(out);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.example.kafka.Item e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeFloat(this.totalPrice);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readInt();

      if (this.user == null) {
        this.user = new com.example.kafka.UserInfo();
      }
      this.user.customDecode(in);

      if (this.shippingAddress == null) {
        this.shippingAddress = new com.example.kafka.Address();
      }
      this.shippingAddress.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<com.example.kafka.Item> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.example.kafka.Item>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.example.kafka.Item> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.kafka.Item>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.example.kafka.Item e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.example.kafka.Item();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.totalPrice = in.readFloat();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readInt();
          break;

        case 1:
          if (this.user == null) {
            this.user = new com.example.kafka.UserInfo();
          }
          this.user.customDecode(in);
          break;

        case 2:
          if (this.shippingAddress == null) {
            this.shippingAddress = new com.example.kafka.Address();
          }
          this.shippingAddress.customDecode(in);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<com.example.kafka.Item> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.example.kafka.Item>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.example.kafka.Item> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.kafka.Item>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.example.kafka.Item e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.example.kafka.Item();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 4:
          this.totalPrice = in.readFloat();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










